// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TreasuryYields.Repositories.Contexts.Implementations;

namespace TreasuryYields.API.Migrations
{
    [DbContext(typeof(TreasuryYieldsDbContext))]
    [Migration("20210827122758_AddFromString")]
    partial class AddFromString
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("TreasuryYields.Models.Entities.TreasuryYieldsDay", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double?>("FiveYears")
                        .HasColumnType("double precision");

                    b.Property<string>("From")
                        .HasColumnType("text");

                    b.Property<double?>("OneMonths")
                        .HasColumnType("double precision");

                    b.Property<double?>("OneYears")
                        .HasColumnType("double precision");

                    b.Property<double?>("SevenYears")
                        .HasColumnType("double precision");

                    b.Property<double?>("SixMonths")
                        .HasColumnType("double precision");

                    b.Property<double?>("TenYears")
                        .HasColumnType("double precision");

                    b.Property<double?>("ThirtyYears")
                        .HasColumnType("double precision");

                    b.Property<double?>("ThreeMonths")
                        .HasColumnType("double precision");

                    b.Property<double?>("ThreeYears")
                        .HasColumnType("double precision");

                    b.Property<double?>("TwentyYears")
                        .HasColumnType("double precision");

                    b.Property<double?>("TwoMonths")
                        .HasColumnType("double precision");

                    b.Property<double?>("TwoYears")
                        .HasColumnType("double precision");

                    b.HasKey("ID");

                    b.ToTable("TreasuryYieldsDays");
                });
#pragma warning restore 612, 618
        }
    }
}
